import {
    brinkPink,
    cadetBlue, cultured,
    darkCyan,
    green,
    maxBlueGreen,
    neutral,
    radicalRed, raisinBlack,
    red,
    redMunsell,
    yellow
} from "./colors";
import {primaryFont} from "./typography";


export const lightTheme = {
    secondaryWrapperColor: raisinBlack,
    primaryWrapperColor: cultured,
    iconColor: neutral[600],
    primaryColor: radicalRed,
    primaryColorHover: brinkPink,
    primaryColorActive: redMunsell,
    textColorOnPrimary: neutral[100],
    textColor: neutral[600],
    textColorInverted: neutral[100],
    subTextColor: neutral[300],
    primaryColorDisabled: neutral[400],
    textColorOnDisabled: neutral[100],
    formElementBackground: neutral[100],
    formElementText: neutral[600],
    formHeaderWrapper: neutral[100],
    formHeaderWrapperText: neutral[600],
    status: {
        warningColor: yellow[200],
        warningColorHover: yellow[100],
        warningColorActive: yellow[300],
        dangerColor: red[200],
        dangerColorHover: red[100],
        dangerColorActive: red[300],
        successColor: green[200],
        successColorHover: green[100],
        successColorActive: green[300],
    },
    primaryFont,
};

export const defaultTheme = {
    primaryWrapperColor: raisinBlack,
    secondaryWrapperColor: cultured,
    iconColor: neutral[100],
    primaryColor: cadetBlue,
    primaryColorHover: maxBlueGreen,
    primaryColorActive: darkCyan,
    textColorOnPrimary: neutral[100],
    textColor: neutral[100],
    textColorInverted: raisinBlack,
    subTextColor: neutral[300],
    primaryColorDisabled: neutral[400],
    textColorOnDisabled: neutral[100],
    formElementBackground: cultured,
    formElementText: neutral[600],
    formHeaderWrapper: raisinBlack,
    formHeaderWrapperText: neutral[100],
    status: {
        warningColor: yellow[200],
        warningColorHover: yellow[100],
        warningColorActive: yellow[300],
        dangerColor: red[200],
        dangerColorHover: red[100],
        dangerColorActive: red[300],
        successColor: green[200],
        successColorHover: green[100],
        successColorActive: green[300],
    },
    primaryFont,
};